const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "5000";
CONSTANTS.ENDPOINT.HOME = "/";
CONSTANTS.ENDPOINT.EMAIL = "/email";
CONSTANTS.ENDPOINT.REPO = "/repos";
CONSTANTS.ENDPOINT.REPO_FILTER = "/repos/find";
CONSTANTS.ENDPOINT.GITHUB_USER = "/users";
CONSTANTS.ENDPOINT.LANGUAGES = "/repos/languages";

module.exports = CONSTANTS;
